/-
  Machine-checked theorem index for the SpinorLean paper surface.
-/

import Spinor.Covering
import Spinor.ComplexClassification
import Spinor.RealClassification
import Spinor.Cl03QuaternionProd
import Spinor.Cl60QuaternionMatrix

/-!
# Machine-checked theorem index

This module intentionally contains no new definitions. It imports the public theorem-facing
surface used by the paper and `#check`s the declarations cited in `THEOREM_INDEX.md`. Keeping
this file in the normal `lake build` makes theorem-name drift visible to CI and reviewers.
-/

#check Spinor.HyperbolicPresentation
#check Spinor.HyperbolicPresentation.spinorModule
#check Spinor.HyperbolicPresentation.cliffordAction
#check Spinor.HyperbolicPresentation.spinRepresentation
#check Spinor.HyperbolicPresentation.cliffordEquivEnd
#check Spinor.HyperbolicPresentation.cliffordEquivMatrix
#check Spinor.splitSpinorModule
#check Spinor.positiveHalfSpinorModule
#check Spinor.negativeHalfSpinorModule

#check Spinor.splitCliffordAction_surjective
#check Spinor.splitCliffordAction_injective
#check Spinor.splitWittCliffordEquivMatrix

#check Spinor.evenSplitCliffordEquivProdEnd
#check Spinor.evenSplitCliffordAction_isSimpleModule
#check Spinor.oddSplitCliffordAction_isSimpleModule
#check Spinor.not_nonempty_evenOddSplitCliffordLinearEquiv
#check Spinor.positiveHalfSpinorModule_eq_evenWittExterior
#check Spinor.negativeHalfSpinorModule_eq_oddWittExterior
#check Spinor.splitSpinor_chiral_correspondence

#check Spinor.HyperbolicPresentation.ofIsCompl
#check Spinor.wittPresentation
#check Spinor.splitWittPresentation
#check Spinor.splitSpinorCliffordAction_sq_apply
#check Spinor.splitSpinorCliffordAction_injective
#check Spinor.splitSpinorModule_finrank
#check Spinor.positiveHalfSpinorModule_finrank
#check Spinor.negativeHalfSpinorModule_finrank

#check Spinor.spinIsometryRepresentation
#check Spinor.spinSpecialOrthogonalRepresentationFiniteDimensional
#check Spinor.spinLinearRepresentation_det_eq_one

#check Spinor.HyperbolicPresentation.spinRepresentation_not_factor_through_isometry_of_pos_finrank
#check Spinor.splitSpinRepresentation_not_factor_through_isometry
#check Spinor.positiveHalfSpinRepresentation_not_factor_through_isometry
#check Spinor.negativeHalfSpinRepresentation_not_factor_through_isometry

#check Spinor.spinSpecialOrthogonalRepresentationFiniteDimensional_range_dualProdLine_eq_squareScalingSubgroup
#check Spinor.spinSpecialOrthogonalRepresentationFiniteDimensional_surjective_dualProdLine_iff_square_surjective
#check Spinor.spinSpecialOrthogonalRepresentationFiniteDimensional_not_surjective_dualProdLine_of_exists_nonsquare_unit
#check Spinor.spinSpecialOrthogonalRepresentationFiniteDimensional_covering_dualProdLine_iff_square_surjective
#check Spinor.units_square_surjective_of_isAlgClosed
#check Spinor.spinSpecialOrthogonalRepresentationFiniteDimensional_surjective_dualProdLine_of_isAlgClosed
#check Spinor.spinSpecialOrthogonalRepresentationFiniteDimensional_covering_dualProdLine_of_isAlgClosed

#check Spinor.HyperbolicPresentation.submodule_map_spinRepresentation_eq_of_spinIsometryRepresentation_eq
#check Spinor.splitSpinorSubmodule_map_spinRepresentation_eq_of_spinIsometryRepresentation_eq
#check Spinor.positiveHalfSpinorSubmodule_map_spinRepresentation_eq_of_spinIsometryRepresentation_eq
#check Spinor.negativeHalfSpinorSubmodule_map_spinRepresentation_eq_of_spinIsometryRepresentation_eq
#check Spinor.splitSpinorSubmoduleImageAction
#check Spinor.positiveHalfSpinorSubmoduleImageAction
#check Spinor.negativeHalfSpinorSubmoduleImageAction

#check ExteriorAlgebra.topExteriorCoeff
#check ExteriorAlgebra.topExteriorPairing
#check ExteriorAlgebra.topExteriorPairing_one_topExteriorGenerator
#check Spinor.topExteriorPairing_wedgeAction_left
#check Spinor.topExteriorPairing_contractionAction_left
#check Spinor.topExteriorPairing_splitGeneratorAction_left
#check Spinor.topExteriorPairing_splitCliffordAction_reverse_left
#check Spinor.eq_algebraMap_of_forall_contractionAction_eq_zero
#check Spinor.splitCliffordAction_eq_smul_exteriorMap_of_spinSpecialOrthogonalRepresentation_eq
#check Spinor.splitCliffordAction_eq_units_smul_exteriorMap_of_spinSpecialOrthogonalRepresentation_eq
#check Spinor.splitCliffordAction_apply_one_and_topExteriorGenerator_of
#check Spinor.splitCliffordAction_topExteriorCoeff_of_spinSpecialOrthogonalRepresentation_eq
#check Spinor.splitCliffordAction_topExteriorCoeff_pairing_of_units_smul_exteriorMap
#check Spinor.exists_det_eq_sq_of_spinSpecialOrthogonalRepresentation_eq_of_topExteriorCoeff_pairing
#check Spinor.exists_det_eq_sq_of_spinSpecialOrthogonalRepresentation_eq

#check Spinor.dualProdTransvectionCliffordUnit
#check Spinor.coe_dualProdTransvectionCliffordUnit
#check Spinor.dualProdTransvectionCliffordUnit_inv_eq
#check Spinor.dualProdTransvectionCliffordUnit_mem_unitary
#check Spinor.dualProdTransvectionCliffordUnit_mem_even
#check Spinor.dualProdTransvectionCliffordUnit_conjAct_eq_transvection
#check Spinor.splitCliffordAction_dualProdTransvectionCliffordUnit_eq_exteriorMap_transvection

#check Spinor.spinSpecialOrthogonalPairGenerator
#check Spinor.lineScalingLinearEquiv
#check Spinor.spinSpecialOrthogonalPairGenerator_eq_lineScalingLinearEquiv
#check Spinor.lineScalingLinearEquiv_mul_transvection_mul_symm_eq
#check Spinor.splitCliffordAction_spinIotaPairOfQuadraticEqNegOne_eq_smul_exteriorMap_lineScaling

#check Spinor.splitCliffordAction_list_prod_basisTransvectionCliffordUnit_eq_exteriorMap_prod
#check Spinor.basisScalingLinearEquiv_det
#check Spinor.basisScalingLinearEquiv_det_update
#check Spinor.exists_basisScalingLinearEquivCliffordUnit_eq_smul_exteriorMap_of_prod_eq_sq
#check Spinor.exists_linearEquivCliffordUnit_eq_smul_exteriorMap_of_det_eq_sq
#check Spinor.exists_linearEquivCliffordUnit_eq_smul_exteriorMap_of_square_surjective
#check Spinor.exists_linearEquivCliffordUnit_eq_smul_exteriorMap_of_isAlgClosed
#check Spinor.dualProdSpecialOrthogonalOf_basisTransvectionLinearEquiv_mem_spin_range
#check Spinor.dualProdSpecialOrthogonalOfLinearEquiv_mem_spin_range_of_det_eq_one
#check Spinor.dualProdSpecialOrthogonalOfLinearEquiv_mem_spin_range_of_det_eq_sq
#check Spinor.dualProdSpecialOrthogonalOfLinearEquiv_mem_spin_range_iff_exists_det_eq_sq
#check Spinor.linearEquivDetSquareClassHom
#check Spinor.linearEquivDetSquareClassHom_eq_one_iff_exists_det_eq_sq
#check Spinor.linearEquivDetSquareClassHom_eq_one_iff_mem_spin_range
#check Spinor.linearEquivDetSquareClassHom_surjective
#check Spinor.linearEquivSpinImageSubgroup
#check Spinor.linearEquivDetSquareClassHom_ker_eq_spin_image_subgroup
#check Spinor.linearEquivSpinImageSubgroup_normal
#check Spinor.linearEquivSpinImageQuotientEquivSquareClass
#check Spinor.linearEquivSpinImageQuotientEquivSquareClass_mk
#check Spinor.linearEquivSplitLeviSpinorNormHom
#check Spinor.linearEquivSplitLeviSpinorNormHom_apply
#check Spinor.linearEquivSplitLeviSpinorNormHom_surjective
#check Spinor.linearEquivSplitLeviSpinorNormHom_ker_eq_spin_image_subgroup
#check Spinor.linearEquivSplitLeviSpinorNormQuotientEquivSquareClass
#check Spinor.linearEquivSplitLeviSpinorNormQuotientEquivSquareClass_mk
#check Spinor.dualProdLeviDetSquareClassHom
#check Spinor.dualProdLeviDetSquareClassHom_apply_equiv_eq_one_iff_mem_spin_range
#check Spinor.dualProdLeviDetSquareClassHom_ker_eq_spin_image_comap
#check Spinor.dualProdLeviDetSquareClassHom_surjective
#check Spinor.dualProdLeviSpinImageSubgroup
#check Spinor.dualProdLeviSpinImageSubgroup_normal
#check Spinor.dualProdLeviSpinImageQuotientEquivSquareClass
#check Spinor.dualProdLeviSpinImageQuotientEquivSquareClass_mk
#check Spinor.dualProdLeviSpinorNormHom
#check Spinor.dualProdLeviSpinorNormHom_apply_equiv
#check Spinor.dualProdLeviSpinorNormHom_surjective
#check Spinor.dualProdLeviSpinorNormHom_ker_eq_spin_image_comap
#check Spinor.dualProdLeviSpinorNormQuotientEquivSquareClass
#check Spinor.dualProdLeviSpinorNormQuotientEquivSquareClass_mk
#check Spinor.dualProdSpecialOrthogonalOfLinearEquiv_mem_spin_range_of_square_surjective
#check Spinor.dualProdSpecialOrthogonalOfLinearEquiv_mem_spin_range_of_isAlgClosed
#check Spinor.dualProdSpecialOrthogonalOf_basisTransvectionLinearEquiv_mem_spin_range_of_two_lt_card
#check Spinor.dualProdSpecialOrthogonalOfLinearEquiv_mem_spin_range_of_det_eq_one_of_two_lt_card
#check Spinor.dualProdSpecialOrthogonalOfLinearEquiv_mem_spin_range_of_det_eq_sq_of_two_lt_card
#check Spinor.dualProdSpecialOrthogonalOfLinearEquiv_mem_spin_range_of_square_surjective_of_two_lt_card

#check Spinor.complexEvenCliffordEquivMatrix
#check Spinor.complexOddCliffordEquivProdMatrix
#check Spinor.realSplitCliffordEquivMatrix
#check Spinor.realSplitEvenCliffordEquivProdMatrix
#check Spinor.RealClassification.cl_n_n_equivMatrix
#check Spinor.RealClassification.cl_n_n_even_equivProdMatrix
#check Spinor.RealClassification.cl_succ_n_n_equivProdMatrix
#check Spinor.RealClassification.cl_0_0_equivReal
#check Spinor.RealClassification.cl_1_0_equivRealProd
#check Spinor.RealClassification.cl_1_0_even_equivReal
#check Spinor.RealClassification.cl_0_1_equivComplex
#check Spinor.RealClassification.cl_0_1_even_equivReal
#check Spinor.RealClassification.cl_0_2_equivQuaternion
#check Spinor.RealClassification.cl_0_2_even_equivComplex
#check Spinor.realCl20EquivMatrix2
#check Spinor.RealClassification.cl_2_0_equivMatrix2
#check Spinor.RealClassification.cl_2_0_even_equivComplex
#check Spinor.realCl30EquivComplexMatrix2
#check Spinor.RealClassification.cl_3_0_equivComplexMatrix2
#check Spinor.RealClassification.cl_3_0_even_equivQuaternion
#check Spinor.RealClassification.cl_0_3_equivQuaternionProd
#check Spinor.RealClassification.cl_0_3_even_equivQuaternion
#check Spinor.realCl04EquivQuaternionMatrix2
#check Spinor.RealClassification.cl_0_4_equivQuaternionMatrix2
#check Spinor.RealClassification.cl_0_4_even_equivQuaternionProd
#check Spinor.realEvenCl05EquivQuaternionMatrix2
#check Spinor.RealClassification.cl_0_5_even_equivQuaternionMatrix2
#check Spinor.realCl05EquivComplexMatrix4
#check Spinor.RealClassification.cl_0_5_equivComplexMatrix4
#check Spinor.realCl40EquivQuaternionMatrix2
#check Spinor.RealClassification.cl_4_0_equivQuaternionMatrix2
#check Spinor.realEvenCl40EquivQuaternionProd
#check Spinor.RealClassification.cl_4_0_even_equivQuaternionProd
#check Spinor.realEvenCl50EquivQuaternionMatrix2
#check Spinor.RealClassification.cl_5_0_even_equivQuaternionMatrix2
#check Spinor.realCl50EquivQuaternionMatrix2Prod
#check Spinor.RealClassification.cl_5_0_equivQuaternionMatrix2Prod
#check Spinor.realEvenCl06EquivComplexMatrix4
#check Spinor.RealClassification.cl_0_6_even_equivComplexMatrix4
#check Spinor.realCl06EquivRealMatrix8Block
#check Spinor.realCl06EquivRealMatrix8
#check Spinor.RealClassification.cl_0_6_equivMatrix8
#check Spinor.realEvenCl60EquivComplexMatrix4
#check Spinor.RealClassification.cl_6_0_even_equivComplexMatrix4
#check Spinor.realCl60EquivQuaternionMatrix4Block
#check Spinor.realCl60EquivQuaternionMatrix4
#check Spinor.RealClassification.cl_6_0_equivQuaternionMatrix4
#check Spinor.RealClassification.cl_1_1_equivMatrix2
#check Spinor.RealClassification.cl_1_1_even_equivRealProd
#check Spinor.RealClassification.cl_2_2_equivMatrix4
#check Spinor.RealClassification.cl_2_2_even_equivProdMatrix2
#check Spinor.realOddSplitPositiveCliffordEquivProdMatrix

#check Spinor.realSpin02EquivUnitaryComplex
#check Spinor.realSpin03EquivUnitaryQuaternion
#check Spinor.realSpin04EquivUnitaryQuaternionPair
